name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v5
      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm
      - name: install npm dependencies
        run: npm install
      - name: Rrn build
        run: npm run build:firefox
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
