name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm

      - name: Install npm dependencies
        run: npm install

      - name: Run build
        run: npm run build:firefox

      - name: Zip extensions
        run: zip extensions.zip ./build -r

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extensions.zip
          path: extensions.zip
